import { StrictMode, useEffect, useState, type FormEvent } from 'react';
import { createRoot } from 'react-dom/client';
import type { Session } from '@supabase/supabase-js';
import { createSupabaseClient } from './lib/supabase';
import { loadPublicConfig } from './config';
import './styles.css';

type Tenant = { id: string; name: string; slug: string; status: string };
type Project = { id: string; name: string; status: string; created_at: string };
type IntegrationStatus = { configured: boolean; connected: boolean; accountEmail: string | null; accountLabel: string | null; lastError: string | null };
let supabase: ReturnType<typeof createSupabaseClient> = null;
let apiUrl = '';

function App() {
  const [session, setSession] = useState<Session | null>(null);
  const [tenant, setTenant] = useState<Tenant | null>(null);
  const [projects, setProjects] = useState<Project[]>([]);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [newPassword, setNewPassword] = useState('');
  const [workspaceName, setWorkspaceName] = useState(''); const [workspaceSlug, setWorkspaceSlug] = useState(''); const [projectName, setProjectName] = useState(''); const [sourceUrl, setSourceUrl] = useState('');
  const [mustChangePassword, setMustChangePassword] = useState(false); const [showProjectForm, setShowProjectForm] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [googleStatus, setGoogleStatus] = useState<{ drive: IntegrationStatus; youtube: IntegrationStatus } | null>(null); const [googleNotice, setGoogleNotice] = useState<{ provider: 'drive' | 'youtube' | null; message: string }>({ provider: null, message: '' });

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const result = params.get('google');
    if (!result) return;
    const provider = params.get('provider') === 'youtube' ? 'youtube' : params.get('provider') === 'drive' ? 'drive' : null;
    const messages: Record<string, string> = { connected: 'conectado com sucesso.', denied: 'A autorização foi negada.', invalid: 'Retorno inválido do Google.', expired: 'A sessão de autorização expirou. Tente novamente.', notokens: 'O Google não retornou tokens utilizáveis.', savefailed: 'Não foi possível salvar a integração.' };
    setGoogleNotice({ provider, message: messages[result] ?? '' });
    window.history.replaceState({}, '', window.location.pathname);
  }, []);

  useEffect(() => { if (!supabase) return; supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data } = supabase.auth.onAuthStateChange((_event, next) => setSession(next)); return () => data.subscription.unsubscribe(); }, []);
  useEffect(() => { const client = supabase; if (!client || !session) return; client.from('profiles').select('must_change_password').eq('id', session.user.id).single().then(({ data }) => setMustChangePassword(Boolean(data?.must_change_password))); fetch(`${apiUrl}/v1/me`, { headers: { Authorization: `Bearer ${session.access_token}` } }).then(response => response.json()).then(data => setTenant(data.memberships?.[0]?.tenants ?? null)); }, [session]);
  useEffect(() => { const client = supabase; if (!client || !tenant) return; const load = () => client.from('projects').select('id, name, status, created_at').eq('tenant_id', tenant.id).order('created_at', { ascending: false }).then(({ data }) => setProjects(data ?? [])); load(); const channel = client.channel(`tenant:${tenant.id}:jobs`).on('postgres_changes', { event: '*', schema: 'public', table: 'processing_jobs', filter: `tenant_id=eq.${tenant.id}` }, load).subscribe(); return () => { client.removeChannel(channel); }; }, [tenant]);
  useEffect(() => { const client = supabase; if (!client || !session || !tenant) return; loadIntegrations(); }, [session, tenant]);
  async function loadIntegrations() { if (!session || !tenant) return; fetch(`${apiUrl}/v1/integrations/google/status?tenant_id=${tenant.id}`, { headers: { Authorization: `Bearer ${session.access_token}` } }).then(response => response.json()).then(data => setGoogleStatus(data)).catch(() => setGoogleStatus(null)); }
  async function connectIntegration(provider: 'drive' | 'youtube') { setBusy(true); setError(''); try { const response = await fetch(`${apiUrl}/v1/integrations/google/start?tenant_id=${tenant!.id}&provider=${provider}`, { headers: { Authorization: `Bearer ${session!.access_token}` } }); const data = await response.json(); if (!response.ok || !data.url) { setError(data.error ?? 'Não foi possível iniciar a conexão.'); return; } window.location.href = data.url; } finally { setBusy(false); } }
  async function disconnectIntegration(provider: 'drive' | 'youtube') { setBusy(true); setError(''); try { const response = await fetch(`${apiUrl}/v1/integrations/google/disconnect?tenant_id=${tenant!.id}&provider=${provider}`, { method: 'DELETE', headers: { Authorization: `Bearer ${session!.access_token}` } }); const data = await response.json(); if (!response.ok) { setError(data.error ?? 'Não foi possível desconectar.'); return; } setGoogleNotice({ provider, message: 'desconectado.' }); await loadIntegrations(); } finally { setBusy(false); } }
  function integrationCard(provider: 'drive' | 'youtube') {
    const st = googleStatus?.[provider];
    const isDrive = provider === 'drive';
    const name = isDrive ? 'Google Drive' : 'YouTube';
    const desc = isDrive ? 'Armazena cortes, áudios e transcrições no Drive do workspace.' : 'Publica Shorts e verifica o canal no YouTube.';
    return <div className="google-card" key={provider}><div className="google-icon">{isDrive ? '▤' : '▶'}</div><div><span className="eyebrow">{isDrive ? 'DRIVE INTEGRATION' : 'YOUTUBE INTEGRATION'}</span><h2>{name}</h2>{st?.connected ? <p className="muted">Conectado como <b>{st.accountLabel ?? st.accountEmail ?? 'conta Google'}</b>.</p> : st?.configured ? <p className="muted">{desc}</p> : <p className="muted">Integração não configurada no servidor.</p>}</div>{st?.configured && <button disabled={busy} onClick={() => st?.connected ? disconnectIntegration(provider) : connectIntegration(provider)}>{st?.connected ? 'Desconectar' : 'Conectar'} <span>↗</span></button>}{googleNotice?.provider === provider && googleNotice.message && <div className="notice">{googleNotice.message}</div>}</div>;
  }
  async function signIn(event: FormEvent) { event.preventDefault(); setError(''); if (!supabase) return setError('Supabase ainda não foi configurado.'); const result = await supabase.auth.signInWithPassword({ email, password }); if (result.error) setError('E-mail ou senha inválidos.'); }
  async function changePassword(event: FormEvent) { event.preventDefault(); setError(''); if (!supabase) return; const result = await supabase.auth.updateUser({ password: newPassword }); if (result.error) return setError('Use uma senha forte com pelo menos 12 caracteres.'); const profile = await supabase.from('profiles').update({ must_change_password: false }).eq('id', session!.user.id); if (profile.error) return setError('Senha alterada, mas o perfil não foi atualizado.'); setMustChangePassword(false); }
  async function createWorkspace(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); const response = await fetch(`${apiUrl}/v1/tenants`, { method: 'POST', headers: { Authorization: `Bearer ${session!.access_token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ name: workspaceName, slug: workspaceSlug }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setError(data.error ?? 'Não foi possível criar o workspace.'); setTenant(data.tenant); }
  async function createProject(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); const response = await fetch(`${apiUrl}/v1/projects`, { method: 'POST', headers: { Authorization: `Bearer ${session!.access_token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ tenant_id: tenant!.id, name: projectName, source_url: sourceUrl }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setError(data.error ?? 'Não foi possível criar o projeto.'); setProjects(current => [data.project, ...current]); setProjectName(''); setSourceUrl(''); setShowProjectForm(false); }
  if (!session) return <main className="auth"><section className="hero"><span className="eyebrow">CLIPCON / AI CONTENT OS</span><h1>Do episódio longo ao seu próximo momento viral.</h1><p>Organize, encontre e transforme os melhores momentos do seu conteúdo em Shorts.</p></section><form className="card login" onSubmit={signIn}><div><span className="eyebrow">WORKSPACE ACCESS</span><h2>Entrar no ClipCon</h2><p className="muted">Acesse seu workspace com segurança.</p></div><label>E-mail<input type="email" required value={email} onChange={event => setEmail(event.target.value)} /></label><label>Senha<input type="password" required value={password} onChange={event => setPassword(event.target.value)} /></label>{error && <div className="error">{error}</div>}<button type="submit">Entrar no workspace <span>↗</span></button></form></main>;
  if (mustChangePassword) return <main className="auth"><form className="card login" onSubmit={changePassword}><span className="eyebrow">SECURITY CHECK</span><h2>Atualize sua senha</h2><p className="muted">Por segurança, altere a senha inicial antes de continuar.</p><label>Nova senha<input type="password" minLength={12} required value={newPassword} onChange={event => setNewPassword(event.target.value)} /></label>{error && <div className="error">{error}</div>}<button type="submit">Salvar nova senha <span>↗</span></button></form></main>;
  if (!tenant) return <main className="auth"><form className="card login" onSubmit={createWorkspace}><span className="eyebrow">FIRST WORKSPACE</span><h2>Crie seu workspace</h2><p className="muted">Um workspace mantém seus projetos e arquivos isolados.</p><label>Nome<input required value={workspaceName} onChange={event => setWorkspaceName(event.target.value)} placeholder="Minha produtora" /></label><label>Slug<input required value={workspaceSlug} onChange={event => setWorkspaceSlug(event.target.value)} placeholder="minha-produtora" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /></label>{error && <div className="error">{error}</div>}<button disabled={busy} type="submit">Criar workspace <span>↗</span></button></form></main>;
  return <main className="app"><header><div className="brand"><b>CLIP</b>CON</div><div><span className="workspace-label">{tenant.name}</span><div className="avatar">{session.user.email?.[0]?.toUpperCase()}</div></div></header><section className="welcome"><span className="eyebrow">OVERVIEW / {tenant.slug.toUpperCase()}</span><h1>Seu conteúdo, em movimento.</h1><p>O próximo corte começa com uma boa conversa.</p><div className="grid"><div className="card metric"><span className="muted">Projetos ativos</span><strong>{projects.filter(project => project.status === 'active').length}</strong><small>Projetos neste workspace</small></div><div className="card metric"><span className="muted">Cortes gerados</span><strong>0</strong><small>Os resultados aparecerão aqui</small></div><div className="card metric accent"><span className="muted">Pipeline</span><strong>Pronto</strong><small>Jobs acompanham progresso em tempo real</small></div></div><div className="integrations">{integrationCard('drive')}{integrationCard('youtube')}{error && <div className="error">{error}</div>}</div><div className="section-heading"><div><span className="eyebrow">PROJECTS</span><h2>Seus projetos</h2></div><button onClick={() => setShowProjectForm(true)}>Novo projeto <span>＋</span></button></div>{showProjectForm && <form className="card project-form" onSubmit={createProject}><label>Nome do projeto<input required value={projectName} onChange={event => setProjectName(event.target.value)} placeholder="Podcast Ep. 42" /></label><label>URL do YouTube<input required type="url" value={sourceUrl} onChange={event => setSourceUrl(event.target.value)} placeholder="https://youtube.com/watch?v=..." /></label>{error && <div className="error">{error}</div>}<button disabled={busy} type="submit">Enfileirar processamento <span>↗</span></button></form>}{projects.length === 0 && !showProjectForm ? <div className="card empty"><div className="play">✦</div><h2>Crie seu primeiro projeto</h2><p>Insira um vídeo longo do YouTube para iniciar o pipeline.</p><button onClick={() => setShowProjectForm(true)}>Começar agora <span>↗</span></button></div> : <div className="project-list">{projects.map(project => <article className="card project" key={project.id}><div className="play">◌</div><div><h3>{project.name}</h3><span className="muted">{project.status === 'active' ? 'Processamento pronto para iniciar' : 'Arquivado'}</span></div><span className="status">{project.status}</span></article>)}</div>}</section></main>;
}
async function bootstrap() {
  try {
    const publicConfig = await loadPublicConfig();
    supabase = createSupabaseClient(publicConfig);
    apiUrl = publicConfig.apiUrl ?? '';
    createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
  } catch {
    document.getElementById('root')!.innerHTML = '<main class="auth"><section class="card login"><span class="eyebrow">CONFIGURATION ERROR</span><h2>Não foi possível carregar o workspace.</h2><p class="muted">A configuração pública do ClipCon não está disponível no momento.</p></section></main>';
  }
}
bootstrap();
